import Foundation

/// A large static library of motivational lines. No AI involved — the quote
/// shown rotates to a different one every few hours, chosen pseudo-randomly but
/// deterministically per time-window so it's stable until it changes.
enum DailyQuotes {

    /// Returns the quote for the current time window. Changes roughly every
    /// four hours to a different, well-distributed pick.
    static func current(now: Date = Date()) -> String {
        guard !all.isEmpty else { return "Start where you are. Use what you have. Do what you can." }
        let windowHours = 4.0
        let bucket = Int(now.timeIntervalSince1970 / (3600.0 * windowHours))
        // LCG-style mix so consecutive windows land on very different indices.
        let mixed = UInt64(bitPattern: Int64(bucket)) &* 6364136223846793005 &+ 1442695040888963407
        return all[Int(mixed % UInt64(all.count))]
    }

    static let all: [String] = [
        "Small daily improvements are how staggering results are built.",
        "You don't have to be extreme — just consistent.",
        "Discipline is choosing what you want most over what you want now.",
        "The work you avoid today is the work that waits for you tomorrow.",
        "Motivation gets you started. Habit keeps you going.",
        "A goal without a daily action is just a wish.",
        "Show up on the days you don't feel like it — that's where it's won.",
        "Progress, not perfection.",
        "One pulse at a time is how mountains get moved.",
        "The hardest rep is the one that builds you.",
        "You can't out-plan the work. Eventually you just do it.",
        "Done beats perfect every single time.",
        "Today's effort is tomorrow's foundation.",
        "Consistency compounds. So does quitting.",
        "Start before you're ready — readiness comes from starting.",
        "Your future self is watching what you do right now.",
        "Tiny steps still move you forward.",
        "The streak protects the goal. Don't break the chain.",
        "Comfort is a slow way to lose.",
        "What you repeat, you become.",
        "Hard now, easy later. Easy now, hard later.",
        "You won't always be motivated, so learn to be disciplined.",
        "The plan is simple. Following it is the hard part — and the whole point.",
        "Action cures fear.",
        "If it matters, do it daily.",
        "The best time to start was yesterday. The second best time is now.",
        "You rise to the level of your habits, not your hopes.",
        "Win the morning, win the day.",
        "Effort is the one variable entirely in your control.",
        "Every expert was once a beginner who refused to quit.",
        "Slow progress is still progress. Don't stop.",
        "Make it so small you can't say no.",
        "Pressure is a privilege — it means you're chasing something real.",
        "The dip is where most people quit. Push one more day.",
        "You are one decision away from a completely different day.",
        "Don't count the days. Make the days count.",
        "Energy follows action, not the other way around.",
        "Discipline weighs ounces. Regret weighs tons.",
        "Be the kind of person who finishes.",
        "Focus on the next pulse, not the whole mountain.",
        "Repetition is the mother of mastery.",
        "Your habits are voting for who you'll become.",
        "The goal is a direction, the habit is the vehicle.",
        "Do the boring work brilliantly.",
        "Greatness is just consistency dressed in patience.",
        "If you're tired, learn to rest — not to quit.",
        "Stop waiting for perfect conditions. Begin in this one.",
        "What gets scheduled gets done.",
        "You don't find time. You make it.",
        "The standard you walk past is the standard you accept.",
        "Discomfort is the price of admission to a better life.",
        "Aim for one percent better than yesterday.",
        "Momentum is built, not found.",
        "Talk less about it. Do more of it.",
        "Quiet consistency beats loud ambition.",
        "Your only competition is who you were yesterday.",
        "Build the system and the results take care of themselves.",
        "When you feel like stopping, that's usually the moment that counts.",
        "The reps you skip are the ones you'll feel later.",
        "Patience plus persistence is unstoppable.",
        "Show your goal you're serious — today.",
        "Excuses or results. You only get to keep one.",
        "Make discipline your default, not your decision.",
        "Direction matters more than speed.",
        "Keep your promises to yourself first.",
        "The grind is quiet. The results are loud.",
        "Decide once, then just execute.",
        "Don't break the streak for a feeling that passes by tomorrow.",
        "Become addicted to the process and the outcome chases you.",
        "Effort today, evidence tomorrow.",
        "You can do hard things — you've done them before.",
        "A little progress each day adds up to big results.",
        "Falling behind is recoverable. Quitting is not.",
        "Stack the days and the weeks take care of themselves.",
        "Be relentless on the small stuff.",
        "Your goals don't care how you feel — show up anyway.",
        "The first step is the heaviest. Lift it.",
        "Trade instant comfort for lasting pride.",
        "Earn the rest by doing the work.",
        "Dreams written down with deadlines become plans.",
        "If the plan scares you a little, it's probably the right size.",
        "Outlast the doubt.",
        "Master the basics before you chase the flashy.",
        "Today is a clean rep. Make it count.",
        "The path is made by walking it.",
        "You don't rise to the occasion — you fall to your training.",
        "Practice doesn't make perfect. It makes permanent. Practice well.",
        "Choose the discomfort that grows you.",
        "Be impatient with actions and patient with results.",
        "When in doubt, do the next right thing.",
        "Habits are the compound interest of self-improvement.",
        "Don't negotiate with the snooze button.",
        "The work is the reward.",
        "Stay in the game long enough to get good.",
        "Make the decision once and protect it daily.",
        "A goal is a promise to your future self — keep it.",
        "You can rest, but don't you dare retreat.",
        "Average effort done daily beats heroic effort done once.",
        "Pick the goal, then fall in love with the routine.",
        "Cut the goal into pulses small enough to win.",
        "Show up tired. Show up unsure. Just show up.",
        "Inch by inch, anything's a cinch.",
        "Your habits today are your headlines tomorrow.",
        "Begin again, as many times as it takes.",
        "Don't fear slow. Fear stopped.",
        "Build proof, not promises.",
        "Hold the line on the days that test you.",
        "The compound effect is real — keep feeding it.",
        "Action is the antidote to anxiety.",
        "Make today a link in a long, unbroken chain.",
        "What you do consistently shapes who you consistently are.",
        "Resist the urge to quit on a hard day.",
        "Be stubborn about the goal, flexible about the method.",
        "One honest hour beats ten distracted ones.",
        "You're closer than the doubt is telling you.",
        "Set the bar at 'I showed up.' Then clear it daily.",
        "Let your actions be louder than your intentions.",
        "Plant today what you want to harvest later.",
        "The streak is sacred. Defend it.",
        "Hard work beats talent when talent skips the reps.",
        "Keep going — quitting guarantees nothing changes.",
        "Make your future self proud with this next pulse.",
        "Discipline is just love for your goals in action.",
        "Win today. Repeat tomorrow.",
        "Steady feet finish the race.",
        "The only bad workout is the one you talked yourself out of.",
        "Do it scared. Do it tired. Just do it daily.",
        "Your goal is built in the boring middle. Stay there.",
        "Effort is a skill. Practice it.",
        "Don't wait to feel ready. Move and let belief catch up.",
    ]
}
